### ISSUE TITLE
Websocket Server?

### ISSUE THREAD

**Issue by nkev** [tidwall/evio#16]
Would this library a good use case for a websocket server, like https://github.com/gobwas/ws ?

**Comment by tidwall** [comment]
Yes. I think Evio would be perfect as a websocket server.

**Comment by tidwall** [comment]
I'm closing this issue for now, but please feel free to reopen if needed.

**Comment by ytkang** [comment]
@tidwall 

Hi I tried to use Evio for websocket. but I stopped. because there are two problems. 

1. Read
- websocket read should be done by their libaray. messages should be separated by websocket protocol. but Evio looks like just read all.
- what about adding like this "events.DataEvent(c Conn)" so user can read using websocket library.

2. Write
- write can be divided actually write to buffer and flush them. so user can reduce system call. but Evio seems calling every write.
- what about just using channel to write for a client? instead of waking..
