### ISSUE TITLE
Listen FD register twice?

### ISSUE THREAD

**Issue by huiwq1990** [tidwall/evio#27]
For tcp server, evio uses `net.Listen` to start listen, then use `netln.File()` (evio_unix.go line 505) dup listen fd. Evio's epoll use the dup fd listen events. When call `net.Listen`, golang also register listen fd to netpoll, evio has not operation on this fd.  So, the same file (fd  not equal) register in seperate epoll.

My question is :
1) why evio not use `syscall.Socket` to get listen fd.
```
fd, err := syscall.Socket(syscall.AF_INET, syscall.O_NONBLOCK|syscall.SOCK_STREAM, 0)
```
2) do they have impact on server performance? 
As, file event will trigger two epoll.

Thanks.

**Comment by tidwall** [comment]
> why evio not use syscall.Socket to get listen fd.

I liked that the Go team did such a good job with net.Listen. I don't have to worry about configuring for udp or tcp4/6 or unix pipes. I can just call net.Listen with the proto type and get the fd back for my purpose.

> do they have impact on server performance?

I'm not encountering a noticeable difference in performance when compared to acquiring a listener socket from a `syscall.Socket`.

But I suspect there's a small penalty somewhere in there due to having two epolls listening on read events for the same socket. Probably when an incoming socket needs accepting there's a 50/50 chance it'll hit the wrong epoll the first time.

I wonder if there's a clean way to deregister from the Go netpoll, prior to registering to the evio epoll?

**Comment by huiwq1990** [comment]
Yes, register to custom epoll will be very good. Do you have any progress about this?
